version: '3.3'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 80:80
    networks: 
      mto_net:
    depends_on:
    - grafana

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
    - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
    - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
    - gfa_data:/var/lib/grafana
    ports:
    - 3000:3000
    networks:
      mto_net:
       ipv4_address: 172.18.0.10

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
    - ./prometheus/:/etc/prometheus/
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
    - 9090:9090
    networks:
      mto_net:
       ipv4_address: 172.18.0.20

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    command:
    - "--path.rootfs=/host"
    volumes:
    - "/:/host:ro,rslave"
    pid: host
    ports:
    - 9100:9100
    networks:
      mto_net:
       ipv4_address: 172.18.0.30

networks:
  mto_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24

volumes:
  gfa_data: {}

